#! /bin/sh

hsetroot -solid "#34322e"

bspc config border_width        4
bspc config window_gap          30
bspc config top_padding         24

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
