#!/bin/sh

hsetroot -full ~/pictures/andromeda.jpg

bspc config border_width        4
bspc config window_gap          30
bspc config top_padding         24

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color "#424242"
bspc config active_border_color "#4d69ff"
bspc config focused_border_color "#9e9e9e"
bspc config presel_border_color "#eeeeee"
bspc config urgent_border_color "#e00032"
bspc config focused_locked_border_color "#aa00ff"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
